#!/usr/bin/env python3
"""Regenerate stat_overrides.json from STAT_HINTS.md.

STAT_HINTS.md is the human-edited source of truth for per-category hint/reach
numbers. The game only reads stat_overrides.json (see models._load_overrides),
so this script keeps the two in sync: edit STAT_HINTS.md, run this, commit, deploy.

In STAT_HINTS.md each category block looks like:

    Career RBI (MLB)  [mlb_career_rbi]
    HINT=1500 REACH=2000  ELIGIBLE=Y  rows=7624

(underscores/brackets may be markdown-escaped with backslashes.)

Usage:
    py build_overrides.py            # write stat_overrides.json
    py build_overrides.py --check    # exit 1 if the file is out of date (CI/pre-commit)
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
MD_PATH = os.path.join(ROOT, "STAT_HINTS.md")
JSON_PATH = os.path.join(ROOT, "stat_overrides.json")

COMMENT = (
    "GENERATED by build_overrides.py from STAT_HINTS.md - do not hand-edit. "
    "Edit STAT_HINTS.md then run `py build_overrides.py`. "
    'hint = number shown on the club; reach = value used for hole sizing. '
    "Restart after deploy (git pull && sudo systemctl restart statgolf)."
)

TAG_RE = re.compile(r"\[([^\]]+)\]")
HR_RE = re.compile(r"HINT=\s*([0-9.]+)\s*REACH=\s*([0-9.]+)\s*ELIGIBLE=\s*([YN])")


def _num(s):
    f = float(s)
    return int(f) if f.is_integer() else f


def parse_md(text):
    """Return {category: {'hint': n, 'reach': n}} for every block with HINT/REACH.
    First valid occurrence of a category wins."""
    lines = text.splitlines()
    out = {}
    for i, line in enumerate(lines):
        m = TAG_RE.search(line)
        if not m:
            continue
        cat = m.group(1).replace("\\", "")          # strip markdown backslash-escapes
        if not re.fullmatch(r"[a-z0-9_]+", cat) or cat in out:
            continue                                 # not a category tag, or already captured
        for j in range(i, min(i + 4, len(lines))):   # HINT/REACH is on the next line or two
            hr = HR_RE.search(lines[j])
            if hr:
                out[cat] = {"hint": _num(hr.group(1)), "reach": _num(hr.group(2))}
                break
    return out


def build():
    overrides = parse_md(open(MD_PATH, encoding="utf-8").read())
    # Sort by reach descending (then hint, then name) so the file stays stable & readable.
    ordered = dict(sorted(
        overrides.items(),
        key=lambda kv: (-kv[1]["reach"], -kv[1]["hint"], kv[0]),
    ))
    doc = {"_comment": COMMENT, "overrides": ordered}
    return json.dumps(doc, indent=2) + "\n"


def main():
    new = build()
    check = "--check" in sys.argv
    current = open(JSON_PATH, encoding="utf-8").read() if os.path.exists(JSON_PATH) else ""
    n = new.count('"hint"')
    if check:
        if new != current:
            print("stat_overrides.json is OUT OF DATE - run: py build_overrides.py", file=sys.stderr)
            return 1
        print(f"stat_overrides.json up to date ({n} categories).")
        return 0
    with open(JSON_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write(new)
    print(f"Wrote stat_overrides.json from STAT_HINTS.md ({n} categories).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
